name: Woohoo
email: martin.james.robinson@gmail.com
author: Martin Robinson
description: Abandoned Wig blog
url: http://abandonedwig.info
exclude: [ generate-blog ]
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title:output_ext
